In [1]:
import pandas as pd

### LOAD DATA

In [56]:
df=pd.read_excel("Employee Sample Data - A.xlsx")

In [57]:
print(df.to_string())

       EEID             Full Name                       Job Title       Department           Business Unit  Gender  Ethnicity   Age  Hire Date  Annual Salary  Bonus %        Country            City  Exit Date
0    E02387           Emily Davis                      Sr. Manger               IT  Research & Development  Female      Black  55.0 2016-04-08       141604.0     0.15  United States         Seattle 2021-10-16
1    E04105         Theodore Dinh             Technical Architect               IT           Manufacturing    Male      Asian  59.0 1997-11-29        99975.0     0.00          China       Chongqing        NaT
2    E02572          Luna Sanders                        Director          Finance     Speciality Products  Female  Caucasian  50.0 2006-10-26       163099.0     0.20  United States         Chicago        NaT
3    E02832       Penelope Jordan        Computer Systems Manager               IT           Manufacturing  Female  Caucasian  26.0 2019-09-27        84913.0     0.07  United States         Chicago        NaT
4    E01639             Austin Vo                     Sr. Analyst          Finance           Manufacturing    Male      Asian  55.0 1995-11-20        95409.0     0.00  United States         Phoenix        NaT
5    E00644          Joshua Gupta          Account Representative            Sales               Corporate    Male      Asian  57.0 2017-01-24        50994.0     0.00          China       Chongqing        NaT
6    E01550           Ruby Barnes                         Manager               IT               Corporate  Female  Caucasian  27.0 2020-07-01       119746.0     0.10  United States         Phoenix        NaT
7    E04332           Luke Martin                         Analyst          Finance           Manufacturing    Male      Black  25.0 2020-05-16        41336.0     0.00  United States           Miami 2021-05-20
8    E04533         Easton Bailey                         Manager       Accounting           Manufacturing    Male  Caucasian  29.0 2019-01-25       113527.0     0.06  United States          Austin        NaT
9    E03838       Madeline Walker                     Sr. Analyst          Finance     Speciality Products  Female  Caucasian  34.0 2018-06-13        77203.0     0.00  United States         Chicago        NaT
10   E00591          Savannah Ali                      Sr. Manger  Human Resources           Manufacturing  Female      Asian  36.0 2009-02-11       157333.0     0.15  United States           Miami        NaT
11   E03344         Camila Rogers               Controls Engineer      Engineering     Speciality Products  Female  Caucasian  27.0 2021-10-21            NaN     0.00  United States         Seattle        NaT
12   E00530             Eli Jones                         Manager  Human Resources           Manufacturing    Male  Caucasian  59.0 1999-03-14       105086.0     0.09  United States          Austin        NaT
13   E04239          Everleigh Ng                      Sr. Manger          Finance  Research & Development  Female        NaN  51.0 2021-06-10       146742.0     0.10          China        Shanghai        NaT
14   E03496           Robert Yang                     Sr. Analyst       Accounting     Speciality Products    Male      Asian  31.0 2017-11-04        97078.0     0.00  United States          Austin 2020-03-09
15   E00549           Isabella Xi                  Vice President        Marketing  Research & Development  Female      Asian  41.0 2013-03-13       249270.0     0.30  United States         Seattle        NaT
16   E00163          Bella Powell                        Director          Finance  Research & Development  Female      Black  65.0 2002-03-04       175837.0     0.20  United States         Phoenix        NaT
17   E00884          Camila Silva                      Sr. Manger        Marketing     Speciality Products  Female     Latino  64.0 2003-12-01       154828.0      NaN  United States         Seattle        NaT
18   E04116          David Barnes                             NaN               IT               Corporate    Male  Caucasian  64.0 2013-11-03       186503.0     0.24  United States        Columbus        NaT
19   E04625             Adam Dang                        Director            Sales  Research & Development    Male      Asian  45.0 2002-07-09       166331.0     0.18          China       Chongqing        NaT
20   E03680        Elias Alvarado                      Sr. Manger               IT           Manufacturing    Male     Latino  56.0 2012-01-09       146140.0     0.10         Brazil          Manaus        NaT
21   E04732            Eva Rivera                        Director            Sales           Manufacturing  Female     Latino  36.0 2021-04-02       151703.0     0.21  United States           Miami        NaT
22   E03484          Logan Rivera                        Director               IT  Research & Development    Male     Latino  59.0 2002-05-24       172787.0     0.28         Brazil  Rio de Janerio        NaT
23   E00671        Leonardo Dixon                         Analyst            Sales     Speciality Products    Male  Caucasian  37.0 2019-09-05        49998.0     0.00  United States         Seattle        NaT
24   E02071             Mateo Her                  Vice President            Sales     Speciality Products    Male      Asian  44.0 2014-03-02       207172.0     0.31          China       Chongqing        NaT
25   E02206        Jose Henderson                        Director  Human Resources     Speciality Products    Male      Black  41.0 2015-04-17       152239.0     0.23  United States        Columbus        NaT
26   E04545         Abigail Mejia                Quality Engineer      Engineering               Corporate  Female     Latino  56.0 2005-02-05        98581.0     0.00         Brazil  Rio de Janerio        NaT
27   E00154            Wyatt Chin                  Vice President      Engineering     Speciality Products    Male      Asian  43.0 2004-06-07       246231.0     0.31  United States         Seattle        NaT
28   E03343             Carson Lu             Engineering Manager      Engineering     Speciality Products    Male      Asian  64.0 1996-12-04        99354.0     0.12          China         Beijing        NaT
29   E00304            Dylan Choi                  Vice President               IT               Corporate    Male      Asian  63.0 2012-05-11       231141.0     0.34          China         Beijing        NaT
30   E02594         Ezekiel Kumar                  IT Coordinator               IT  Research & Development    Male      Asian  28.0 2017-06-25        54775.0     0.00  United States        Columbus        NaT
31   E00402        Dominic Guzman                         Analyst          Finance           Manufacturing    Male     Latino  65.0 2004-05-16        55499.0     0.00         Brazil          Manaus        NaT
32   E01994          Angel Powell                      Analyst II            Sales  Research & Development    Male  Caucasian  61.0 2008-07-11        66521.0     0.00  United States         Seattle        NaT
33   E03549              Mateo Vu          Account Representative            Sales     Speciality Products    Male      Asian  30.0 2016-09-29        59100.0     0.00          China       Chongqing        NaT
34   E03247      Caroline Jenkins                         Analyst          Finance  Research & Development  Female  Caucasian  27.0 2018-05-06        49011.0     0.00  United States         Chicago        NaT
35   E02074            Nora Brown            Enterprise Architect               IT           Manufacturing  Female  Caucasian  32.0 2014-02-11        99575.0     0.00  United States          Austin        NaT
36   E04152         Adeline Huang               Controls Engineer      Engineering           Manufacturing  Female      Asian  34.0 2019-12-16        99989.0     0.00          China         Chengdu        NaT
37   E01628         Jackson Perry                  Vice President        Marketing  Research & Development    Male  Caucasian  27.0 2019-10-20       256420.0     0.30  United States         Phoenix        NaT
38   E04285         Riley Padilla             Technical Architect               IT           Manufacturing  Female     Latino  35.0 2013-05-15        78940.0     0.00  United States           Miami        NaT
39   E01417             Leah Pena            Enterprise Architect               IT               Corporate  Female     Latino  57.0 1994-01-03        82872.0     0.00         Brazil          Manaus        NaT
40   E01754              Owen Lam            Sr. Business Partner  Human Resources     Speciality Products    Male      Asian  30.0 2017-05-29        86317.0     0.00          China         Chengdu 2017-07-16
41   E03749        Kennedy Foster                         Manager        Marketing     Speciality Products  Female  Caucasian  53.0 2013-11-23       113135.0     0.05  United States          Austin        NaT
42   E03574            John Moore                  Vice President               IT     Speciality Products    Male  Caucasian  52.0 2005-11-08       199808.0     0.32  United States         Seattle        NaT
43   E04600            William Vu          Account Representative            Sales     Speciality Products    Male      Asian  37.0 2013-11-14        56037.0     0.00          China        Shanghai        NaT
44   E00586      Sadie Washington                      Sr. Manger        Marketing  Research & Development  Female  Caucasian  29.0 2019-05-24       122350.0     0.12  United States         Phoenix        NaT
45   E03538        Gabriel Holmes            Enterprise Architect               IT  Research & Development    Male  Caucasian   NaN 2010-11-04        92952.0     0.00  United States         Seattle        NaT
46   E02185           Wyatt Rojas        Computer Systems Manager               IT               Corporate    Male     Latino  32.0 2013-03-20        79921.0     0.05  United States          Austin        NaT
47   E03830           Eva Coleman                        Director               IT  Research & Development  Female      Black  37.0 2009-09-20       167199.0     0.20  United States         Seattle        NaT
48   E03720         Dominic Clark                Quality Engineer      Engineering  Research & Development    Male  Caucasian  52.0 2012-10-17        71476.0     0.00  United States         Phoenix        NaT
49   E03025        Lucy Alexander                        Director      Engineering           Manufacturing  Female  Caucasian  45.0 2014-10-29       189420.0     0.20  United States         Seattle        NaT
50   E04917  Everleigh Washington                    HRIS Analyst  Human Resources  Research & Development  Female  Caucasian  64.0 2001-10-20        64057.0     0.00  United States         Phoenix        NaT
51   E00415        Leilani Butler                      Analyst II        Marketing           Manufacturing  Female      Black  27.0 2021-09-21        68728.0     0.00  United States         Phoenix        NaT
52   E02862          Peyton Huang                      Sr. Manger               IT           Manufacturing  Female      Asian  25.0 2021-07-02       125633.0     0.11          China         Beijing        NaT
53   E04207        John Contreras                      Analyst II        Marketing           Manufacturing    Male     Latino  35.0 2011-05-15        66889.0     0.00  United States        Columbus        NaT
54   E02139              Rylee Yu                        Director       Accounting  Research & Development  Female      Asian  36.0 2015-09-29       178700.0     0.29  United States         Seattle        NaT
55   E01797           Piper Lewis                  Field Engineer      Engineering  Research & Development  Female  Caucasian  33.0 2018-12-22            NaN     0.00  United States         Chicago        NaT
56   E01839      Stella Alexander             Automation Engineer      Engineering               Corporate  Female  Caucasian  52.0 2005-12-10       102043.0     0.00  United States         Chicago        NaT
57   E01633            Addison Do             Operations Engineer      Engineering           Manufacturing  Female      Asian  46.0 2001-05-30        90678.0     0.00  United States        Columbus        NaT
58   E01848          Zoey Jackson                Business Partner              NaN           Manufacturing  Female      Black  46.0 2008-08-21        59067.0     0.00  United States           Miami        NaT
59   E00716             John Chow                      Sr. Manger        Marketing  Research & Development    Male      Asian  45.0 2021-03-11       135062.0     0.15          China         Chengdu        NaT
60   E00699             Ava Ayala                      Sr. Manger               IT               Corporate  Female     Latino  55.0 2006-08-16       159044.0     0.10         Brazil          Manaus        NaT
61   E00502       Natalia Salazar                     Sr. Analyst       Accounting           Manufacturing  Female     Latino  44.0 2019-01-02        74691.0     0.00         Brazil          Manaus 2020-07-08
62   E04000       Skylar Carrillo             Engineering Manager      Engineering               Corporate  Female     Latino  44.0 2008-12-18        92753.0     0.13  United States          Austin 2021-06-24
63   E02112     Christian Sanders                  Vice President  Human Resources     Speciality Products    Male      Black  45.0 2013-08-07       236946.0     0.37  United States         Seattle        NaT
64   E03824      Penelope Coleman                         Analyst          Finance               Corporate  Female      Black  36.0 2021-08-27        48906.0     0.00  United States           Miami        NaT
65   E03906      Piper Richardson                     Sr. Analyst            Sales               Corporate  Female  Caucasian  38.0 2008-01-27        80024.0     0.00  United States        Columbus        NaT
66   E00436         Everly Walker                    HRIS Analyst  Human Resources     Speciality Products  Female  Caucasian  41.0 2009-10-23        54415.0     0.00  United States         Seattle 2014-01-22
67   E04798            Aurora Ali                         Manager        Marketing  Research & Development  Female      Asian  30.0 2016-04-24       120341.0     0.07  United States         Seattle        NaT
68   E01249     Penelope Guerrero                  Vice President               IT     Speciality Products  Female     Latino  43.0 2009-08-04       208415.0     0.35  United States         Seattle        NaT
69   E03349            Anna Mehta  Cloud Infrastructure Architect               IT     Speciality Products  Female      Asian  32.0 2020-01-05        78844.0     0.00  United States         Seattle        NaT
70   E02966        William Foster                  Field Engineer      Engineering           Manufacturing    Male  Caucasian  58.0 2002-05-23        76354.0     0.00  United States         Phoenix 2021-09-26
71   E01499            Jade Rojas                        Director          Finance     Speciality Products  Female     Latino  37.0 2019-01-28       165927.0     0.20  United States         Phoenix        NaT
72   E00105         Isla Espinoza                         Manager       Accounting     Speciality Products  Female     Latino  38.0 2021-11-16       109812.0     0.09         Brazil          Manaus        NaT
73   E00665             David Chu               Controls Engineer      Engineering               Corporate    Male      Asian  55.0 1998-09-03        86299.0     0.00  United States         Seattle        NaT
74   E00791        Thomas Padilla                  Vice President        Marketing  Research & Development    Male     Latino  57.0 2003-07-26       206624.0     0.40         Brazil       Sao Paulo        NaT
75   E01540         Miles Salazar                  IT Coordinator               IT           Manufacturing    Male     Latino  36.0 2010-12-23        53215.0     0.00         Brazil       Sao Paulo 2014-03-27
76   E04474             Mila Hong                   Test Engineer      Engineering  Research & Development  Female      Asian  30.0 2017-05-22        86858.0     0.00          China       Chongqing 2017-10-08
77   E03417         Benjamin Moua        Computer Systems Manager               IT           Manufacturing    Male      Asian  40.0 2007-07-02        93971.0     0.08          China       Chongqing        NaT
78   E00254        Samuel Morales                      Analyst II          Finance               Corporate    Male     Latino  34.0 2015-06-27        57008.0     0.00  United States         Phoenix        NaT
79   E02166             John Soto                      Sr. Manger          Finance           Manufacturing    Male     Latino  60.0 2015-09-23       141899.0     0.15  United States         Phoenix        NaT
80   E00935         Joseph Martin                      Analyst II        Marketing               Corporate    Male      Black  41.0 2016-09-13        64847.0     0.00  United States           Miami        NaT
81   E01525             Jose Ross             Engineering Manager      Engineering  Research & Development    Male  Caucasian  53.0 1992-04-08       116878.0     0.11  United States           Miami        NaT
82   E00386          Parker James                Quality Engineer      Engineering     Speciality Products    Male      Black  45.0 2005-02-05        70505.0     0.00  United States          Austin        NaT
83   E00416   Everleigh Fernandez                        Director      Engineering  Research & Development  Female     Latino  30.0 2016-05-22       189702.0     0.28         Brazil          Manaus 2020-12-21
84   E03383          Lincoln Hall                        Director       Accounting     Speciality Products    Male  Caucasian  26.0 2020-07-28       180664.0     0.27  United States         Chicago        NaT
85   E01516            Willow Mai                Business Partner  Human Resources           Manufacturing  Female      Asian  45.0 2003-12-17        48345.0     0.00          China         Chengdu        NaT
86   E01234            Jack Cheng                        Director  Human Resources           Manufacturing    Male      Asian  42.0 2014-01-16       152214.0     0.30          China         Beijing        NaT
87   E03440       Genesis Navarro  Cloud Infrastructure Architect               IT               Corporate  Female     Latino  41.0 2009-04-28        69803.0     0.00         Brazil          Manaus        NaT
88   E00431       Eliza Hernandez               Network Architect               IT               Corporate  Female     Latino  48.0 2019-07-04        76588.0     0.00         Brazil  Rio de Janerio        NaT
89   E01258        Gabriel Brooks                Network Engineer               IT           Manufacturing    Male  Caucasian  29.0 2018-12-10        84596.0     0.00  United States           Miami        NaT
90   E00440            Jack Huynh                         Manager        Marketing  Research & Development    Male      Asian  27.0 2018-09-25       114441.0     0.10          China       Chongqing 2019-12-22
91   E00595           Everly Chow                      Sr. Manger          Finance     Speciality Products  Female      Asian  33.0 2018-04-21       140402.0     0.15          China         Beijing        NaT
92   E00972        Amelia Salazar                      Analyst II          Finance               Corporate  Female     Latino  26.0 2019-04-23        59817.0     0.00         Brazil       Sao Paulo        NaT
93   E04562          Xavier Zheng          Account Representative            Sales           Manufacturing    Male      Asian  31.0 2017-07-22        55854.0     0.00  United States          Austin        NaT

In [58]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   EEID           1000 non-null   object
 1   Full Name      998 non-null    object
 2   Job Title      999 non-null    object
 3   Department     998 non-null    object
 4   Business Unit  1000 non-null   object
 5   Gender         999 non-null    object
 6   Ethnicity      993 non-null    object
 7   Age            994 non-null    float64
 8   Hire Date      993 non-null    datetime64[ns]
 9   Annual Salary  989 non-null    float64
 10  Bonus %        992 non-null    float64
 11  Country        998 non-null    object
 12  City           998 non-null    object
 13  Exit Date      85 non-null     datetime64[ns]
dtypes: datetime64[ns](2), float64(3), object(9)
memory usage: 109.5+ KB

### CLEAN DATA

In [59]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
995    False
996    False
997    False
998    False
999    False
Length: 1000, dtype: bool

In [60]:
df.isnull()

,EEID,Full Name,Job Title,Department,Business Unit,Gender,Ethnicity,Age,Hire Date,Annual Salary,Bonus %,Country,City,Exit Date
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,True
2,False,False,False,False,False,False,False,False,False,False,False,False,False,True
3,False,False,False,False,False,False,False,False,False,False,False,False,False,True
4,False,False,False,False,False,False,False,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,False,False,False,False,False,False,False,False,False,False,False,False,False,True
996,False,False,False,False,False,False,False,False,False,False,False,False,False,False
997,False,False,False,False,False,False,False,False,False,False,False,False,False,True
998,False,False,False,False,False,False,False,False,False,False,False,False,False,True
999,False,False,False,False,False,False,False,False,False,False,False,False,False,True

In [61]:
df.isnull().sum()

EEID               0
Full Name          2
Job Title          1
Department         2
Business Unit      0
Gender             1
Ethnicity          7
Age                6
Hire Date          7
Annual Salary     11
Bonus %            8
Country            2
City               2
Exit Date        915
dtype: int64

In [62]:
df['Is_Exited'] = df['Exit Date'].notnull().astype(int)

In [63]:
df['Age']=df['Age'].fillna(df['Age'].median())
df['Annual Salary']=df['Annual Salary'].fillna(df['Annual Salary'].median())
df['Bonus %']=df['Bonus %'].fillna(df['Bonus %'].median())

In [64]:
df['Age'].median()

45.0

In [65]:
df.isnull().sum()

EEID               0
Full Name          2
Job Title          1
Department         2
Business Unit      0
Gender             1
Ethnicity          7
Age                0
Hire Date          7
Annual Salary      0
Bonus %            0
Country            2
City               2
Exit Date        915
Is_Exited          0
dtype: int64

In [66]:
df['Gender'] = df['Gender'].fillna(df['Gender'].mode()[0])
df['Country'] = df['Country'].fillna(df['Country'].mode()[0])

df['Department'] = df['Department'].fillna("Unknown")
df['City'] = df['City'].fillna("Unknown")
df['Ethnicity'] = df['Ethnicity'].fillna("Unknown")
df['Job Title'] = df['Job Title'].fillna("Unknown")

df['Hire Date'] = df['Hire Date'].fillna(df['Hire Date'].median())

In [67]:
df.isnull().sum()

EEID               0
Full Name          2
Job Title          0
Department         0
Business Unit      0
Gender             0
Ethnicity          0
Age                0
Hire Date          0
Annual Salary      0
Bonus %            0
Country            0
City               0
Exit Date        915
Is_Exited          0
dtype: int64

In [68]:
df = df.dropna(subset=['Full Name'])

In [69]:
df.isnull().sum()

EEID               0
Full Name          0
Job Title          0
Department         0
Business Unit      0
Gender             0
Ethnicity          0
Age                0
Hire Date          0
Annual Salary      0
Bonus %            0
Country            0
City               0
Exit Date        913
Is_Exited          0
dtype: int64

In [70]:
df = df.drop(columns=['Exit Date'])

In [71]:
df.isnull().sum()

EEID             0
Full Name        0
Job Title        0
Department       0
Business Unit    0
Gender           0
Ethnicity        0
Age              0
Hire Date        0
Annual Salary    0
Bonus %          0
Country          0
City             0
Is_Exited        0
dtype: int64

### Modify the first 5 rows

In [73]:
for i in df.head().index:
    df.loc[i, 'Annual Salary']=1000

In [87]:
df.loc[0:4, 'Age'] = [25, 30, 28, 35, 32]
df.loc[0:4, 'Department'] = ['HR', 'IT', 'Finance', 'IT', 'HR']

In [88]:
df.head()

,EEID,Full Name,Job Title,Department,Business Unit,Gender,Ethnicity,Age,Hire Date,Annual Salary,Bonus %,Country,City,Is_Exited
0,E02387,Emily Davis,Sr. Manger,HR,Research & Development,Female,Black,25.0,2016-04-08,1000.0,0.15,United States,Seattle,1
1,E04105,Theodore Dinh,Technical Architect,IT,Manufacturing,Male,Asian,30.0,1997-11-29,1000.0,0.00,China,Chongqing,0
2,E02572,Luna Sanders,Director,Finance,Speciality Products,Female,Caucasian,28.0,2006-10-26,1000.0,0.20,United States,Chicago,0
3,E02832,Penelope Jordan,Computer Systems Manager,IT,Manufacturing,Female,Caucasian,35.0,2019-09-27,1000.0,0.07,United States,Chicago,0
4,E01639,Austin Vo,Sr. Analyst,HR,Manufacturing,Male,Asian,32.0,1995-11-20,1000.0,0.00,United States,Phoenix,0

### largest salary.

In [76]:
df['Annual Salary'].max()

258498.0

In [79]:
new_df=df.groupby('Department')

In [84]:
new_df['Age'].mean()
new_df['Annual Salary'].mean()

Department
Accounting         123146.947917
Engineering        108439.974522
Finance            120848.783333
Human Resources    117907.088710
IT                  96636.991632
Marketing          129663.033333
Sales              111120.635714
Unknown             66902.500000
Name: Annual Salary, dtype: float64

In [85]:
newdf=df.groupby(['Department','Ethnicity'])

In [86]:
newdf['Age'].max()
newdf['Age'].min()
newdf['Annual Salary'].median()

Department       Ethnicity
Accounting       Asian        114893.0
                 Black         91853.0
                 Caucasian    121159.5
                 Latino        92317.0
Engineering      Asian         91230.0
                 Black         74412.0
                 Caucasian     95639.0
                 Latino        96818.0
                 Unknown       96567.0
Finance          Asian        124928.0
                 Black        131652.0
                 Caucasian     95045.0
                 Latino       124553.0
                 Unknown       96567.0
Human Resources  Asian        125871.5
                 Black        142318.0
                 Caucasian    100364.5
                 Latino       101985.0
IT               Asian         89494.0
                 Black         72901.5
                 Caucasian     81218.0
                 Latino        83403.0
                 Unknown       96567.0
Marketing        Asian        147752.0
                 Black         86075.5
                 Caucasian    113135.0
                 Latino        97063.5
Sales            Asian         89528.5
                 Black         94246.0
                 Caucasian     96092.0
                 Latino       113269.0
                 Unknown       96567.0
Unknown          Black         59067.0
                 Caucasian     74738.0
Name: Annual Salary, dtype: float64

In [90]:
df.to_excel('cleaned_data.xlsx', index=False)